# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 13:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(regex=re.compile('^[a-z0-9_.-]+$', 2)), django.core.validators.MinLengthValidator(5)], verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(help_text='Use\'[algo]$[salt]$[hexdigest]\' or use the <a href="password/">change password form</a>.', max_length=128, verbose_name='password')),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=1)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='About')),
                ('timezone', models.SmallIntegerField(default=32000)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avatar_type', models.PositiveIntegerField(choices=[(1, 'Default'), (2, 'Gravatar'), (3, 'Upload')], default=1)),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Is deactivated')),
            ],
        ),
    ]
