# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 14:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_account_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('price_morning', models.FloatField()),
                ('price_afternoon', models.FloatField()),
                ('price_evening', models.FloatField()),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('photo', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
