# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
