# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stadium_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
